-- RC Agents SaaS Core — Database Schema
-- PostgreSQL DDL for reference
-- Auto-generated by SQLAlchemy models, stored here for documentation

-- ============================================================
-- USERS (Tenant owners)
-- ============================================================
CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(36) PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    company VARCHAR(255) DEFAULT '',
    plan VARCHAR(50) NOT NULL DEFAULT 'free',
    plan_status VARCHAR(20) DEFAULT 'active',
    stripe_customer_id VARCHAR(255),
    stripe_subscription_id VARCHAR(255),
    meta_bm_id VARCHAR(255),
    meta_system_user_token TEXT,
    conversations_this_month INTEGER DEFAULT 0,
    billing_period_start TIMESTAMP,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    is_active BOOLEAN DEFAULT TRUE
);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

-- ============================================================
-- STORES (Shopify stores)
-- ============================================================
CREATE TABLE IF NOT EXISTS stores (
    id VARCHAR(36) PRIMARY KEY,
    user_id VARCHAR(36) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    shopify_domain VARCHAR(255) NOT NULL,
    shopify_access_token VARCHAR(255) NOT NULL,
    shopify_store_id VARCHAR(255),
    shopify_location_id VARCHAR(50) DEFAULT '',
    is_connected BOOLEAN DEFAULT TRUE,
    last_sync_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(user_id, shopify_domain)
);

-- ============================================================
-- CHANNELS (Messaging platforms)
-- ============================================================
CREATE TABLE IF NOT EXISTS channels (
    id VARCHAR(36) PRIMARY KEY,
    user_id VARCHAR(36) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    store_id VARCHAR(36) REFERENCES stores(id) ON DELETE SET NULL,
    channel_type VARCHAR(50) NOT NULL,         -- messenger|instagram|whatsapp|telegram
    platform_id VARCHAR(255) NOT NULL,
    platform_name VARCHAR(255),
    access_token TEXT,
    webhook_secret VARCHAR(255),
    intervention_mode BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(user_id, channel_type, platform_id)
);

-- ============================================================
-- CONVERSATIONS
-- ============================================================
CREATE TABLE IF NOT EXISTS conversations (
    id VARCHAR(36) PRIMARY KEY,
    store_id VARCHAR(36) NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
    channel VARCHAR(50) NOT NULL,
    platform_conversation_id VARCHAR(255),
    customer_name VARCHAR(255),
    customer_platform_id VARCHAR(255),
    last_ai_reply TEXT,
    last_user_message TEXT,
    conversation_state JSONB DEFAULT '{}',
    message_count INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(store_id, platform_conversation_id)
);
CREATE INDEX IF NOT EXISTS idx_conv_store_channel ON conversations(store_id, channel);

-- ============================================================
-- MESSAGES
-- ============================================================
CREATE TABLE IF NOT EXISTS messages (
    id VARCHAR(36) PRIMARY KEY,
    conversation_id VARCHAR(36) NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    store_id VARCHAR(36) NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
    role VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,
    content_type VARCHAR(50) DEFAULT 'text',
    image_url TEXT,
    platform_message_id VARCHAR(255),
    channel VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_msg_conv ON messages(conversation_id, created_at);

-- ============================================================
-- AI SETTINGS (Per store)
-- ============================================================
CREATE TABLE IF NOT EXISTS ai_settings (
    id VARCHAR(36) PRIMARY KEY,
    store_id VARCHAR(36) NOT NULL UNIQUE REFERENCES stores(id) ON DELETE CASCADE,
    system_prompt TEXT DEFAULT '',
    ai_model VARCHAR(100) DEFAULT '',
    temperature FLOAT DEFAULT 0.7,
    max_tokens INTEGER DEFAULT 2048,
    product_catalog JSONB DEFAULT '[]',
    faq_entries JSONB DEFAULT '[]',
    language VARCHAR(10) DEFAULT 'ar',
    greeting_enabled BOOLEAN DEFAULT TRUE,
    greeting_message TEXT DEFAULT '',
    updated_at TIMESTAMP DEFAULT NOW()
);

-- ============================================================
-- INVOICES
-- ============================================================
CREATE TABLE IF NOT EXISTS invoices (
    id VARCHAR(36) PRIMARY KEY,
    user_id VARCHAR(36) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    store_id VARCHAR(36) REFERENCES stores(id) ON DELETE SET NULL,
    plan VARCHAR(50) NOT NULL,
    amount_usd FLOAT NOT NULL,
    amount_dzd FLOAT,
    currency VARCHAR(3) DEFAULT 'USD',
    status VARCHAR(20) DEFAULT 'pending',
    payment_method VARCHAR(50),
    payment_id VARCHAR(255),
    period_start TIMESTAMP NOT NULL,
    period_end TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    paid_at TIMESTAMP
);
